### ISSUE TITLE
Exact definition of the twiss parameters should be put into the Physics guide.

### ISSUE THREAD

**Issue by kparasch** [xsuite/xsuite#161]
In particular, the definition of parameters related to "momentum deviation" can be confusing (e.g. chromaticity, momentum compaction, slip factor, synchrotron tune e.t.c.).

**Comment by giadarol** [comment]
In general twiss should be documented

**Comment by giadarol** [comment]
Not really, in xsuite the chromaticity is defined as the derivative with respect to delta
