### ISSUE TITLE
Class methods in API reference missing information

### ISSUE THREAD

**Issue by ewaagaard** [xsuite/xsuite#166]
Most of the classes and class methods in the [X-track API](https://xsuite.readthedocs.io/en/latest/apixtrack.html) miss descriptive information about what their functionality and arguments are. Just a few lines, as for instance is the case in the [Cpymad API reference](https://hibtc.github.io/cpymad/automod/cpymad.madx.Madx.html?highlight=chdir#cpymad.madx.Madx.chdir) would be very helpful.

**Comment by giadarol** [comment]
Added extensive docstrings to all methods of xtrack.Line

**Comment by giadarol** [comment]
Situation is much better now
