### ISSUE TITLE
Tests fail without OpenCL installation, even when Pyopencl excluded from env var

### ISSUE THREAD

**Issue by szymonlopaciuk** [xsuite/xsuite#167]
Even when `XOBJECTS_TEST_CONTEXTS` excludes `ContextPyopencl`, some tests are run that rely on pyopencl. Usually, even with a broken OpenCL installation these tests pass, however when none is present, the following happens:

<pre><b>$</b> XOBJECTS_TEST_CONTEXTS=&apos;ContextCpu&apos; pytest xobjects/tests
<b>================================================= test session starts =================================================</b>
platform linux -- Python 3.10.4, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/szymonlopaciuk/xsuite/xobjects
<b>collected 80 items                                                                                                    </b>

xobjects/tests/test_align.py <font color="#4D9A05">.                                                                                  [  1%]</font>
xobjects/tests/test_array.py <font color="#4D9A05">.............                                                                      [ 17%]</font>
xobjects/tests/test_buffer.py <font color="#CC0000">FF</font><font color="#4D9A05">.........</font><font color="#CC0000">                                                                       [ 31%]</font>
xobjects/tests/test_capi.py <font color="#4D9A05">........</font><font color="#CC0000">                                                                            [ 41%]</font>
xobjects/tests/test_chunk.py <font color="#4D9A05">.</font><font color="#CC0000">                                                                                  [ 42%]</font>
xobjects/tests/test_hybrid_class.py <font color="#4D9A05">............</font><font color="#CC0000">                                                                [ 57%]</font>
xobjects/tests/test_kernel.py <font color="#4D9A05">..</font><font color="#CC0000">                                                                                [ 60%]</font>
xobjects/tests/test_linked_array.py <font color="#4D9A05">.</font><font color="#CC0000">                                                                           [ 61%]</font>
xobjects/tests/test_nplike_arrays.py <font color="#4D9A05">....</font><font color="#CC0000">                                                                       [ 66%]</font>
xobjects/tests/test_ref.py <font color="#4D9A05">.....</font><font color="#CC0000">                                                                                [ 72%]</font>
xobjects/tests/test_scalars.py <font color="#4D9A05">..</font><font color="#CC0000">                                                                               [ 75%]</font>
xobjects/tests/test_strides.py <font color="#4D9A05">..</font><font color="#CC0000">                                                                               [ 77%]</font>
xobjects/tests/test_string.py <font color="#4D9A05">......</font><font color="#CC0000">                                                                            [ 85%]</font>
xobjects/tests/test_struct.py <font color="#4D9A05">.........</font><font color="#CC0000">                                                                         [ 96%]</font>
xobjects/tests/test_unionref.py <font color="#4D9A05">...</font><font color="#CC0000">                                                                             [100%]</font>

====================================================== FAILURES =======================================================
<font color="#EF2828"><b>________________________________________________ test_cl_print_devices ________________________________________________</b></font>

    <font color="#729ECF">def</font> <font color="#89E234">test_cl_print_devices</font>():
&gt;       xo.ContextPyopencl.print_devices()

<font color="#EF2828"><b>xobjects/tests/test_buffer.py</b></font>:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<font color="#EF2828"><b>xobjects/xobjects/context_pyopencl.py</b></font>:87: in print_devices
    <font color="#729ECF">for</font> ip, platform <font color="#AC7EA8">in</font> <font color="#34E2E2">enumerate</font>(cl.get_platforms()):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;xobjects.context.ModuleNotAvailable object at 0x7f1cc5087850&gt;, attr = &apos;get_platforms&apos;

    <font color="#729ECF">def</font> <font color="#89E234">__getattr__</font>(<font color="#34E2E2">self</font>, attr):
&gt;       <font color="#729ECF">raise</font> <font color="#34E2E2">NameError</font>(<font color="#34E2E2">self</font>.message)
<font color="#EF2828"><b>E       NameError: pyopencl is not installed. ContextPyopencl is not available!</b></font>

<font color="#EF2828"><b>xobjects/xobjects/context.py</b></font>:142: NameError
<font color="#EF2828"><b>____________________________________________________ test_cl_init _____________________________________________________</b></font>

    <font color="#729ECF">def</font> <font color="#89E234">test_cl_init</font>():
&gt;       ctx = xo.ContextPyopencl(device=<font color="#C3A000">&quot;0.0&quot;</font>)

<font color="#EF2828"><b>xobjects/tests/test_buffer.py</b></font>:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<font color="#EF2828"><b>xobjects/xobjects/context_pyopencl.py</b></font>:128: in __init__
    <font color="#34E2E2">self</font>.platform = cl.get_platforms()[platform]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;xobjects.context.ModuleNotAvailable object at 0x7f1cc5087850&gt;, attr = &apos;get_platforms&apos;

    <font color="#729ECF">def</font> <font color="#89E234">__getattr__</font>(<font color="#34E2E2">self</font>, attr):
&gt;       <font color="#729ECF">raise</font> <font color="#34E2E2">NameError</font>(<font color="#34E2E2">self</font>.message)
<font color="#EF2828"><b>E       NameError: pyopencl is not installed. ContextPyopencl is not available!</b></font>

<font color="#EF2828"><b>xobjects/xobjects/context.py</b></font>:142: NameError
=============================================== short test summary info ===============================================
FAILED xobjects/tests/test_buffer.py::test_cl_print_devices - NameError: pyopencl is not installed. ContextPyopencl ...
FAILED xobjects/tests/test_buffer.py::test_cl_init - NameError: pyopencl is not installed. ContextPyopencl is not av...
<font color="#CC0000">============================================ </font><font color="#EF2828"><b>2 failed</b></font>, <font color="#4D9A05">78 passed</font><font color="#CC0000"> in 2.45s =============================================</font>
base_area = 9.000000e+00base_area = 1.200000e+01</pre>

**Comment by giadarol** [comment]
Done
