### ISSUE TITLE
xobjects: trying to create an array of arrays gives misleading error

### ISSUE THREAD

**Issue by szymonlopaciuk** [xsuite/xsuite#177]
When trying the following:
```python
import xobjects as xo

ArrNUint8 = xo.UInt8[:]
ArrNArr = ArrNUint8[:]
ary = ArrNArr([[42, 43], [44, 45, 56]])
```

We get an error:
```python
xsuite/xobjects/xobjects/array.py:89: ValueError
ValueError: [[42, 43], [44, 45, 56]] not an array
```

I am not sure this is a useful use case, but the error message is misleading.

**Comment by rdemaria** [comment]
It is rather bug, because it should generate an array of arrays.

**Comment by rdemaria** [comment]
`ary = ArrNArr([2, [44, 45, 56]])` indeed works as expected
