### ISSUE TITLE
Return error for non-existing keys

### ISSUE THREAD

**Issue by pbelange** [xsuite/xsuite#179]
I would suggest that xdeps returns an error when trying to access `vars[key]` if `key` does not exists. It makes it hard to explore the dependencies and debug the code. Same thing for `element_refs[el_key]`.

**Comment by giadarol** [comment]
Still, the present behaviour is very error prone... Is there anything we could do about it?

**Comment by rdemaria** [comment]
One option is to wrap `data and refs` in a class (a bit like in madxutils.Mix) that does the following

vars[key]: returns a value or an error if key does not exists
vars[key]=value: set a value and propagate dependencies
vars.eval("key1=key*3+2") set new expression

**Comment by pbelange** [comment]
I think that would be good, it would be a proper pythonic implementation of the deferred expressions of Madx

If I am not mistaken, `vars[key]` returns `None` currently if `key` doesn't exists which prevents the user from using `None` to do quality checks and can lead to errors down the road. 

Anyway, thanks for looking into this!

**Comment by rdemaria** [comment]
Try this example (https://github.com/xsuite/xdeps/blob/main/examples/mad/000_ex_env_saveload.py) and see if it fits your expectation

```
import time

from cpymad.madx import Madx
mad=Madx(stdout=False)
mad.call("lhc.seq")
mad.call("optics.madx")

import xdeps.madxutils

m=xdeps.madxutils.MadxEnv(mad)

m.v.on_x1 #160.0
m.e['mcbcv.5r1.b2']['kick'] #1.639653535504e-05
m.v.on_x1+=1 # update and propagates
m.e['mcbcv.5r1.b2']['kick'] # 1.6499013701009e-05
m.madexpr('on_x1=myonx1*2')
m.v.myonx1=10
m.v.on_x1 # 20
m.e['mcbcv.5r1.b2']['kick'] # 2.0495669193799995e-06
```

**Comment by pbelange** [comment]
`m.e` behaves much better indeed since elements that don't exist return an error and the element itself is returned as a dictionary which is really nice to understand the attributes and play with the element in an intuitive pythonic way. (basicly 0 learning curve for python users from that point onward, which is great).

However, `m.v`  returns a default value of `0` (`int`) for non-existing variables:
```python
>>> m.v.on_x1
160.0

>>> m.v.on_x12345
0
```

**Comment by giadarol** [comment]
An exception is now raised, at least in line.vars
