### ISSUE TITLE
make it more visible which tests run on which contexts

### ISSUE THREAD

**Issue by szymonlopaciuk** [xsuite/xsuite#190]
Currently a lot of tests have a `for context in xo.context.get_test_contexts(): ...` inside going through all available contexts. When a test fails, it is not immediately obvious on which context it failed. Additionally, if the test fails on the first context available, tests will not run on the other contexts. This may not be desirable. One option to fix this would be to create something like:

```python
@on_test_contexts
def test_something(context):
    do_something(context)
```

Underneath, the test would run parametrized for all test contexts (this would be visible in the test logs). This would also make tests more compact.

**Comment by giadarol** [comment]
Tested in xobjects, can now be deployed over the entire suite

**Comment by giadarol** [comment]
Tested in xobjects, can now be deployed over the entire suite

**Comment by giadarol** [comment]
Deployed in the entire suite
