### ISSUE TITLE
 'RFBucketMatcher' misses 'warns' method

### ISSUE THREAD

**Issue by sailew** [xsuite/xsuite#192]
When using the `xpart.generate_matched_gaussian_bunch()` method, I get the error

```
AttributeError: 'RFBucketMatcher' object has no attribute 'warns'
```
Looking in the  'RFBucketMatcher'  class, it seems to be missing the method `warns` called by the command `self.warns`  at several locations.

**Comment by giadarol** [comment]
Should be solved in latest release
