### ISSUE TITLE
Need clean way of freezing longitudinal coordinates

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#206]
Users would like to have frozen and non-frozen tracking methods available at the same time 

We want a general high-level way of handling compile flags. Something like:
```python
tracker.config.freeze_longitudinal = True
tracker.config.synchrotron_radiation = False
...
```

Frozen var example available at:
https://github.com/xsuite/xtrack/blob/main/examples/full_ring/007_test_freeze_vars.py

**Comment by szymonlopaciuk** [comment]
Resolved
