### ISSUE TITLE
Auxiliary tracker doesn't propagate matrix_stability_tol and matrix_responsiveness_tol

### ISSUE THREAD

**Issue by anabramo** [xsuite/xsuite#210]
Problem seems to stem from xtrack.twiss._build_auxiliary_tracker_with_extra_markers

**Comment by giadarol** [comment]
This should already be solved by this logic:
https://github.com/xsuite/xtrack/blob/c39c22728e43a582f4405e7220ebcb381399f1af/xtrack/twiss.py#L88

Can you provide an example showing the problem?

**Comment by giadarol** [comment]
Solved in latest version
