### ISSUE TITLE
Twiss on a cycled line with BeamInteraction element produces different optics

### ISSUE THREAD

**Issue by anabramo** [xsuite/xsuite#211]
The differences observed between the original and the cycled line twiss are around 2%. Attaching a simple case with an FCC-ee lattice showing the issue. It should be noted that the the FCC-ee lattice has synchrotron radiation and tapering of the magnetic strengths in the ring. The differences are possibly not an issue, but rather a by-product of the radiation and tapering.

[cycled_line_twiss.tar.gz](https://github.com/xsuite/xsuite/files/9903249/cycled_line_twiss.tar.gz)

**Comment by giadarol** [comment]
It is indeed an effect of the radiation, exploring different solutions at the moment. Solution should come in an upcoming release

**Comment by giadarol** [comment]
As of v0.23 of xtrack, a MAD-X like twiss which symplectifies the effect of radiation can be obtained with:
```tracker.twiss(radiation_method='kick_as_co')```
