### ISSUE TITLE
xobjects: a test that doesn't really do anything; remove?

### ISSUE THREAD

**Issue by szymonlopaciuk** [xsuite/xsuite#228]
This test https://github.com/xsuite/xobjects/blob/main/tests/test_buffer.py#L143-L170 does not actually use any part of xobjects, just some stuff from numpy and pyopencl. The second `try` actually fails on l. 166 but is silenced in the `except`.

Do we know what the test was supposed to do, or should we maybe just remove it?

(@giadarol, I talked to Riccardo and we couldn't figure it out.)

**Comment by giadarol** [comment]
Must be some leftover. Please remove the test

**Comment by giadarol** [comment]
Done
