### ISSUE TITLE
When regenerating json for hllhc15 example test_match_tune_chroma fails

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#245]
Old json was in the format with elements as list instead of elements as dict. Maybe a bug in Line.to_dict/Line.from_dict?

After sorting this out, we should probably regenerate all the jsons

**Comment by szymonlopaciuk** [comment]
I cannot seem to reproduce this on my machine. This is what I do:

1. clone `git@github.com:lhcopt/hllhc15.git`
2. run `000_sequence_from_optics_repo.py` in `xtrack/test_data/hllhc15_noerrors_nobb`
3. run `001_xtline_from_madseq.py` in the same folder
4. the file `line_w_knobs_and_particle.json` has been regenerated

Then when I run the tests in `test_match_tune_chroma.py` everything passes.

However, the generated `json` file indeed differs: `elements` is now a dictionary and not an array, as per the changes in https://github.com/xsuite/xtrack/commit/2808eb4916fe1206bd94c62bcbdc440411735917.

There is a couple seemingly meaningful changes to the file though:

```diff
...

"mco.8r3.b1": {
                 "__class__": "Multipole",
-                "order": 3,
-                "inv_factorial_order": 0.16666666666666666,
+                "order": 0,
+                "inv_factorial_order": 1.0,
                 "length": 0.066,
                 "hxl": 0.0,
                 "hyl": 0.0,
                 "radiation_flag": 0,
                 "knl": [
-                    0.0,
-                    0.0,
-                    0.0,
                     0.0
                 ],
                 "ksl": [
-                    0.0,
-                    0.0,
-                    0.0,
                     0.0
                 ]
             },
-            {

...

-            {
+            "mcd.8r3.b1": {
                 "__class__": "Multipole",
-                "order": 4,
-                "inv_factorial_order": 0.041666666666666664,
+                "order": 0,
+                "inv_factorial_order": 1.0,
                 "length": 0.066,

...
```

Do you think the above differences could be causing issues together with some of your local changes that I don't experience?

I have also repeated the same on the release/v0.23.5 branch. The generated file is the same, and the tests are also passing for me.

**Comment by giadarol** [comment]
Was not able to reproduce the issue on any another machine. And even on my laptop the problem disappeared after upgrading numpy and scipy
