### ISSUE TITLE
refactoring to_json, to_dict

### ISSUE THREAD

**Issue by rdemaria** [xsuite/xsuite#255]
- remove leading underscore from  _to_dict, _to_json in xobjects
- to_dict: create a dictionary from struct keeping arrays
- to_json: create a nested structure of dict and list only. The output can be used to initialize a full object.
- implement list and `__iter__` for multidimensional arrays 
- consider also providing `__array_interface__`

**Comment by giadarol** [comment]
Not really needed for now. Don’t hesitate to reopen if you have use cases for which present dict/json functionalities are not sufficient.
