### ISSUE TITLE
Inconsistent xtrack.Tracker.twiss for a tapered lattice when at_s argument is used

### ISSUE THREAD

**Issue by anabramo** [xsuite/xsuite#269]
For a tapered lattice, `tracker.twiss()` and `tracker.twiss(at_s=s_pos)` produce different results. An example with a script and a lattice is attached, producing the following results:

beta_x non-tapered: regular twiss=352.5787484597305, at_s twiss=352.5787484597305
beta_x tapered: regular twiss=345.124263962744, at_s twiss=352.5833312779748

It is possible the issue has something to do with `xtrack.twiss._build_auxiliary_tracker_with_extra_markers` not propagating the  tapering correctly to the auxiliary tracker.

[tapering_twiss_test.tar.gz](https://github.com/xsuite/xsuite/files/10383128/tapering_twiss_test.tar.gz)

**Comment by giadarol** [comment]
Solved in xtrack v0.26.0
