### ISSUE TITLE
Need option for non-collective elements to be excluded in twiss calculations.

### ISSUE THREAD

**Issue by freddieknets** [xsuite/xsuite#280]
When setting a `BeamElement` to be collective with the flag `collective=True` a few things are happening:

1. The tracker in C will be split around it, hence, it expects a `track` function in python
2. It won't be able to be back-tracked
3. When performing a twiss calculation, the element is replaced by a `Drift`

and maybe some other things.
I'd like to see these disentangled.

In particular, I have a non-collective element that:

1. Has tracking entirely in C (so the tracker should not be split in parts)
2. Should however not be back-trackable
3. Should also be replaced by a `Drift` in twiss calculations

**Comment by giadarol** [comment]
Handled by using negative ```at_turn``` values in twiss
