### ISSUE TITLE
Twiss is not consistent

### ISSUE THREAD

**Issue by freddieknets** [xsuite/xsuite#281]
I'm trying to get the optics functions at the start of the primary collimator in the LHC lattice.
When I just do a general `twiss` over all elements, or a `twiss` at the exact location of the collimator, I get the same result.
However, when I perform the `twiss` at several s positions (e.g. all collimators), I get a difference in the 0.01 digit - large enough to let half of my initial distribution miss the collimator.

Also, the `twiss` over several s positions is several orders slower than the full `twiss` (even though it is calculating vastly less positions).

Below an MWE (it cannot be an `xcoll` issue, as the collimators are not installed yet - they are just zero-length drifts).

```
import xtrack as xt
import json
with open('examples/machines/lhc_run3_b1.json', 'r') as fid:
   loaded_dct = json.load(fid)
line = xt.Line.from_dict(loaded_dct)
tracker = line.build_tracker()

pos_tcp = line.get_s_position('tcp.c6l7.b1')
id_tcp  = line.element_names.index('tcp.c6l7.b1')
print(f"{pos_tcp=}, {id_tcp=}")

coll_names = [ elem for elem in line.element_names if elem[:2] == 'tc' and elem[-2:-1]=='b' ]

tw1 = tracker.twiss()
tw2 = tracker.twiss(at_s = pos_tcp)
tw3 = tracker.twiss(at_s = line.get_s_position(coll_names))

print(f"Full twiss:                     {tw1['name'][id_tcp]:11} at {tw1['s'][id_tcp]} with betx = {tw1['betx'][id_tcp]}")
print(f"Single element twiss at {pos_tcp}: at {tw2['s'][0]} with betx = {tw2['betx'][0]}")

mask_tcp = abs(tw3['s']-19791.184380362996)<0.1
print(f"Twiss over coll positions:                  at {tw3['s'][mask_tcp][0]} with betx = {tw3['betx'][mask_tcp][0]}")
```

Output:

```
pos_tcp=19791.184380362996, id_tcp=73738
Full twiss:                     tcp.c6l7.b1 at 19791.184380362996 with betx = 141.04194573647382
Single element twiss at 19791.184380362996: at 19791.184380362996 with betx = 141.04194573647382
Twiss over coll positions:                  at 19791.184380362996 with betx = 141.0299478591561
```

**Comment by freddieknets** [comment]
The line fine from the MWE is here:

https://github.com/xsuite/xcoll/blob/TempCrystalEverest/examples/machines/lhc_run3_b1.json

**Comment by giadarol** [comment]
I have investigated a bit the issue.

In the provided example, as the number of markers is larger than 10, the code was removing all the drifts in the line, adding the markers and regenerating all the drifts (this would be faster than cutting drifts in case many thick elements are added.
The regeneration of all the drifts introduces the numerical errors reported here. 

For the upcoming xtrack release we will force the markers to be inserted one by one. This removes the observed discrepancy in the beta function.

**Comment by giadarol** [comment]
Deployed in v0.26.0
