### ISSUE TITLE
[xtrack] Multi-turn Element-by-Element tracking support

### ISSUE THREAD

**Issue by ab-gh** [xsuite/xsuite#296]
After trying to find a solution to track element-by-element, rather than turn-by-turn, I came across the undocumented "special tracker flag" `ONE_TURN_EBE`:

```py
tracker.track(
    particles, 
    num_turns = n_turns, 
    turn_by_turn_monitor = "ONE_TURN_EBE"
)
```

This appears to be triggered by a `ebe_mode` flag, but I cannot locate where `"ONE_TURN_EBE"` is defined, or how to pass `ebe_mode=1` to a `xt.ParticlesMonitor` successfully to enable multi-turn element-by-element tracking.

Is this possible? Could you point me towards where either `"ONE_TURN_EBE"` is defined, or where `ebe_mode` could be exposed in the creation of a `xt.ParticlesMonitor`?

**Comment by giadarol** [comment]
At the moment it is only possible to log element-by-element positions when tracking a single turn. You can refer to this test case for an example:
https://github.com/xsuite/xtrack/blob/e9468e5e746170ba1584bb4cf1ae996c691574ad/tests/test_tracker.py#L21

More advanced logging features could be potentially implemented but this is not planned for the immediate future.

Of course, contributions from the user community are always welcome 😜
