### ISSUE TITLE
Initialise `_xofields` with a list of tuples

### ISSUE THREAD

**Issue by szymonlopaciuk** [xsuite/xsuite#312]
"Overriding" `ParticlesBase` introduced in https://github.com/xsuite/xpart/pull/72 requires that the underlying `xo.Struct`s have an overlapping memory layout. Currently the ordering of `_xofields` matters for that layout, however since `_xofields` is defined as a dictionary, the order is implicit. Python 3.7+ guarantees insertion order, so this is not strictly a problem, but supporting being explicit (list of tuples) could prevent future errors.

**Comment by giadarol** [comment]
To be reopened if/when needed
