### ISSUE TITLE
Inplace option for line.cycle()

### ISSUE THREAD

**Issue by freddieknets** [xsuite/xsuite#316]
Currently, cycling a line does not change a line but returns a new one. Typically we will reassign the original one, as such:

    line = line.cycle(‘ip3’)

However, any pointer to the line will still point to the original (uncycled) line. Consider the following case:

    line = xt.Line.from_dict(…)
    coll_manager = CollimatorManager(…, line=line)
    print(id(coll_manager.line)==id(line))   # True
    line = line.cycle(..)
    print(id(coll_manager.line)==id(line))   # False
    coll_manager.build_tracker()
    line.tracker   # None

This can be addressed by the user by updating the pointer:

    line = line.cycle(..)
    coll_manager.line = line

But this puts the responsibility with the user, and failing to do so, would in some cases create a bug that could pass unnoticed.

An option:

    line = line.cycle(.., inplace=True)

would avoid this problem.

**Comment by giadarol** [comment]
Done
