### ISSUE TITLE
Xsuite publication for citations

### ISSUE THREAD

**Issue by eltos** [xsuite/xsuite#318]
Is there a publication, conference proceeding or the like that you recommend citing when referring to Xsuite?

**Comment by giadarol** [comment]
Hi Eltos, for now there is nothing that fits the purpose, coming probably towards the end of the year.
In the meantime you can probably use the website (xsuite.web.cern.ch, which redirects to the readthedocs pages)

**Comment by giadarol** [comment]
Here the preprint of the HB2023 paper on Xsuite:
https://arxiv.org/pdf/2310.00317.pdf

**Comment by eltos** [comment]
I just noticed that the HB23 proceedings are meanwhile published:
 https://doi.org/10.18429/JACoW-HB2023-TUA2I1
