### ISSUE TITLE
Allow new elements in the backtracker for the aperture loss refinement

### ISSUE THREAD

**Issue by freddieknets** [xsuite/xsuite#329]
When building a backtracker to refine the aperture losses, it automatically assumes that all the `BeamElement` types are already in the line. This is not necessarily true, as the backtrack elements might be different (as is the case for an `EverestCollimator` which uses `InvalidCollimator` as a backtracker).

**Comment by giadarol** [comment]
Backtracking mechanism changed in latest version.
