### ISSUE TITLE
Add monitor for turn-by-turn beam iso-center

### ISSUE THREAD

**Issue by eccortes95** [xsuite/xsuite#341]
It would be practical to have a monitor that only records the beam's isocenter to simulate eg tune and chromaticity measurements. The current implementations are prohibitive for long term simulations where turn-by-turn data requires vast amounts of memory.

**Comment by eltos** [comment]
We (@eccortes95 @rahulgsin) are currently working on an implementation of a time based centroid monitor, similar to the exciter element (time based and with arbitrary sampling frequency) to allow for beam position as well as schottky diagnostics not only for bunched but also coasting beams.

**Comment by eccortes95** [comment]
This issue was addressed by @eltos .
