### ISSUE TITLE
Need native IBS in XSuite

### ISSUE THREAD

**Issue by aghribi** [xsuite/xsuite#349]
Hi,

We would greatly benefit from native **IntraBeam Scattering** in XSuite. Would that be possible ?
For us, this is for FCC-ee (booster).

Thanks
Adnan Ghribi

**Comment by mmiglior** [comment]
Indeed, the inclusion of IBS would be very useful for the Booster of FCC-ee.

Many thanks

Mauro

**Comment by giadarol** [comment]
Growth rate calculations have recently been introduced. IBS kicks for tracking coming soon

**Comment by giadarol** [comment]
IBS kicks are also there now
