### ISSUE TITLE
To do mad_loader and slice_thick_elements

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#351]
- [ ] Optionally import geometric properties (angle, length, e1, e2, fint, hgap, etc.) by value, i.e. discard expressions.
   - [ ] Avoid installing Yrotation and Wedge elements when their angle is zero
- [x] Build dictionary of compounds when elements are exploded in mad loader
   - [x] When building the tracker, build mask array for start compound elements
   - [x]  `Line.insert_elements` and probably other Line methods need to be aware of compounds
   - [x] * Add methods to shift or rotate the compounds
- [x] In makethin handle compounds and apertures
- [ ] Import errors and correctly propagate them in makethin
- [x] Need flexible way to switch between linear (edge) and non-linear (yrot-fringe-wedge) edge effects
- [x] Need better checks for longitudinal plane
- [x] * Need to check that fringe does not affect performance when disabled
- [ ] Need examples in online documentation
- [x] * Check that thick elements are handled correctly in Sequence.
- [x] Thick elements need to be handled in survey

**Comment by szymonlopaciuk** [comment]
Regarding the performance considerations of the "multipurpose" edge element, I did some tests and it seems that we are not paying any significant penalties. I compared the current version of Xtrack with v0.36.5 on a thin PSB lattice in various configurations. The thinned lattice was obtained using the current version of Xtrack prior to the tests, to ensure that we are really working with the same model in both the cases. I timed with `%timeit`, and the results are:

<table>
  <tr>
    <th colspan="3">Xtrack v0.38.3 (current)</th>
     <th colspan="3">Xtrack v0.36.5</th></tr>
  <tr>
    <th>edge: linear</th>
    <th>edge: full</th>
    <th>edge: supressed</th>
    <th>default</th>
    <th>no DipoleEdges<br/>(manually removed)</th>
    <th>filtered DipoleEdges</th></tr>
  <tr>
    <td>3.16s</td>
    <td>5.85s</td>
    <td>3.13s</td>
    <td>3.17s</td>
    <td>3.11s</td>
    <td>3.24s</td>
  </tr>
  <tr>
    <td>+1.6%</td>
    <td>+88%</td>
    <td>+0.6%</td>
    <td>+1.9%</td>
    <td>100%</td>
    <td>+4.2% (zero-len drift penalty?)</td>
  </tr>
</table>

**Comment by giadarol** [comment]
Remaining items will be attacked when sequence will be refactored (2024)
