### ISSUE TITLE
Support thick elements in `Line.from_sequence`

### ISSUE THREAD

**Issue by eltos** [xsuite/xsuite#359]
Thick elements are currently not supported:
 [xtrack/line.py#L320-L322](https://github.com/xsuite/xtrack/blob/6ee038bc81236d22e017e0ce689f039a50abc830/xtrack/line.py#L320-L322)
```python
if _is_thick(node.what): 
     raise NotImplementedError( 
         f'Thick elements currently not implemented: {node.name}')
```

Open questions:
- [ ] What is the reference point for thick elements? For example, MAD-X knows REFER=ENTRY/CENTRE/EXIT for definition of the s-position.

Related:
- https://github.com/xsuite/xtrack/pull/344#issuecomment-1610077140
- https://github.com/xsuite/xsuite/issues/351

**Comment by giadarol** [comment]
Done
