### ISSUE TITLE
xtrack line element names not inferred from line elements

### ISSUE THREAD

**Issue by pkicsiny** [xsuite/xsuite#372]
The snippet below demonstrates the issue:
```
import xobjects as xo
import xtrack as xt
import xfields as xf


context = xo.ContextCpu(omp_num_threads=0)


# create some elements
el_1 = xt.LineSegmentMap(_context=context)
el_1.name = "arc"

el_2 = xt.LongitudinalLimitRect()
el_2.name = "dynap"

el_3 = xt.ParticlesMonitor(start_at_turn=0, stop_at_turn=1, particle_id_range=(0,1))
el_3.name = "mon"

print(el_1.name, el_2.name, el_3.name)

# build tracker
line = xt.Line(elements = [el_1, el_2, el_3])
line.build_tracker(_context=context)

print(line.elements[0].name, line.elements[1].name, line.elements[2].name)

print(line.element_names)
```

the second last line prints: `arc dynap mon`

the last line prints: `('e0', 'e1', 'e2')`

The issue is that the names of the elements are not inferred when I build the tracker. There is the attribute `xt.Line.element_names` but it would be easier if the user didn't have to input manually both the elements and their names, but instead there was a feature that the tracker infers the names of each element automatically.

**Comment by giadarol** [comment]
`element.name` is not really supported by xtrack.
The behavior you describe would require quite some work to ensure consistency in all situations and performance for the deferred expressions. We cannot really plan this in the short term.
