### ISSUE TITLE
Error when initting xp.Particles with nan in zeta or delta

### ISSUE THREAD

**Issue by pkicsiny** [xsuite/xsuite#374]
The below snippet demonstrates the issue:

```
import xpart as xp
import numpy as np

beam = xp.Particles(
        x        = [0,np.nan],
        px       = [0,np.nan],
        y        = [0,np.nan],
        py       = [0,np.nan],
        zeta     = [0,np.nan],
        delta    = [0,np.nan],
        state    = [0,np.nan],
        )

beam2 = xp.Particles(
        x        = [0,0],
        px       = [0,0],
        y        = [0,0],
        py       = [0,0],
        zeta     = [0,0],
        delta    = [0,np.nan],
        state    = [0,0],
        )
```

the first beam will be initted OK, but the second will throw:

`ValueError: The given value [ 0. nan] is not consistent with the computed value [ 0. nan]. Difference: [ 0. nan].`

What happens is that in `xpart/particles/particles_base.py` the energy variables given by the user are compared to values that are computed internally from the other variables, triggered [here](https://github.com/xsuite/xpart/blob/main/xpart/particles/particles_base.py#L1704). The same happens when a zeta variable is nan, triggered [here](https://github.com/xsuite/xpart/blob/main/xpart/particles/particles_base.py#L1744). It doesn't happen with the x,y,px,py variables as these are not computed internally. Also if the corresponding state is set to nan, the error doesn't happen either, so the first initialization above executes fine.

This becomes a pain when doing simulations on lxplus using the [DAG manager](https://batchdocs.web.cern.ch/tutorial/exercise8Intro.html) by having chunked jobs. For example I dump my beam coordinates to a compressed file on EOS after the end of one tracking chunk and for the next chunk, which is a different simulation job, I want to read in the dumped data and init my beam with those coordinates. If one of the dumped deltas or zetas is a nan, due to a particle loss during the tracking, I get the above error.

The function [`_allclose`](https://github.com/xsuite/xpart/blob/main/xpart/particles/particles_base.py#L1580) which does the comparison of the input and internally computed variables uses [`np.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html). This function has an attribute `equal_nan` which is false by default but if set to true the above error can be avoided.

(The purpose of using the DAG is because  with long simulations when one needs to periodically write some output into some file on EOS there can be a "transport endpoint not connected" error that crashes the job. The periodic dumping of data to EOS is motivated because otherwise the RAM on the cluster node can fill up quickly, which kills the job, especially when using particle monitors in xtrack.)

**Comment by giadarol** [comment]
Solved by https://github.com/xsuite/xpart/pull/86

To be merged

**Comment by giadarol** [comment]
Done
