### ISSUE TITLE
beta beating disappears after conversion from thin madx sequence to xtrack line

### ISSUE THREAD

**Issue by pkicsiny** [xsuite/xsuite#378]
The necessary files to run the minimal example are found [here](https://cernbox.cern.ch/s/lMzEVTIKbZRtuc8)

Using cpymad, I have a madx 4IP fcc-ee H sequence and I insert vertical wigglers in it to set a desired vertical emittance. This causes a beta beating.

Afterwards I slice it into a thin lattice then twiss. When I plot the beta_y I see that the maximum values at the 4 IPs are different.

Next I convert this lattice into an xtrack line and twiss, but when I plot the beta_y all maxima are equal, so the beta beating effect disappeared.

I suspect there is some issue when converting the wigglers.

**Comment by giadarol** [comment]
As discussed with @pkicsiny, the beta beating is most likely an issue in the mad-x model. It is in fact not expected if the energy loss from the wigglers is correctly compensated by the tapering.

Don't hesitate to reopen if you see suspicious behaviors on the xsuite side.
