### ISSUE TITLE
xtrack tapering gives suboptimal RF cavity lag

### ISSUE THREAD

**Issue by pkicsiny** [xsuite/xsuite#382]
The minimal example to reproduce the issue is found here: https://cernbox.cern.ch/s/q6zh4vBeOQGhccs

The issue happens with an fcc-ee w lattice. I want to convert the madx sequence into xtrack and twiss with mean synrad and tapering, but the twiss fails. If I don't do tapering the twiss is ok. 

The issue is that the tapering finds a lag which results in a delta offset of order 1e-8, which is too large so the twiss orbit is not closed.

In the example I scan and manually change the lag of the tapered lattice (before twiss) and track with each setting one test particle for one turn and record the delta coordinate. This is shown on the plot below with the black dots. It turns out that the optimum (red line) is far away from the value found by the xtrack tapering (blue line).

![lag_opt](https://github.com/xsuite/xsuite/assets/38734280/8710d72f-c368-4499-a71c-bb2cd1f66a0b)

[Here](https://github.com/xsuite/xtrack/blob/main/xtrack/tapering.py#L110) in `xtrack/tapering.py` it seems that a formula is used to update the lag in the tapering.

**Comment by giadarol** [comment]
I just checked the provided lattice with the xsuite production version and everything seems to work fine.
Could you please test with the latest version of xsuite?

This is the script I used:

```python
import xtrack as xt
import xpart as xp

line = xt.Line.from_json('xtrack_line_w_gianni.json')
line.particle_ref = xp.Particles(mass0=xp.ELECTRON_MASS_EV,
                                 gamma0=156556.09468793)

line.build_tracker()

tw_no_rad = line.twiss()

line.configure_radiation(model='mean')
line.compensate_radiation_energy_loss()

tw = line.twiss()
```

**Comment by giadarol** [comment]
I mark this as solved as I can't reproduce the issue. Don't hesitate to reopen if you see problems also with the latest xsuite version.
