### ISSUE TITLE
xdeps: add unregister in copy_expr

### ISSUE THREAD

**Issue by rdemaria** [xsuite/xsuite#383]
in https://github.com/xsuite/xtrack/blob/e434c57f20ef77d872eb455c1817703f17289ea6/xtrack/line.py#L3434

copy_expr_from is used but inside not check for overwrite is done as in set_value

Either add unregister in copy_expr_from or make a new method if too expensive for from_json

**Comment by giadarol** [comment]
This was solved by recent refactoring
https://github.com/xsuite/xdeps/blame/69ae43c8d2e6e38d98ad1ab4e1e6f1d6b728372d/xdeps/tasks.py#L389
