### ISSUE TITLE
Wrong use of _rename in BeamBeam3d

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#416]
I found in the source:
```
    _rename = {'flag_beamstrahlung': '_flag_beamstrahlung'}
    _rename = {'flag_bhabha': '_flag_bhabha'}
```

The first has no effect. The correct syntax is:
```
    _rename = {'flag_beamstrahlung': '_flag_beamstrahlung', 'flag_bhabha': '_flag_bhabha'}
```

**Comment by pkicsiny** [comment]
Fixed in https://github.com/pkicsiny/xfields. Thanks for pointing out!

**Comment by giadarol** [comment]
Thanks. Is it understood why this was not cought by the tests? Are the tests passing now?

**Comment by giadarol** [comment]
When this is ready for merge please open a PR

**Comment by giadarol** [comment]
done
