### ISSUE TITLE
RF cavity momentum gain for particles with non-nominal charge-to-mass ratio

### ISSUE THREAD

**Issue by elisabethrenner** [xsuite/xsuite#446]
Dear all, 

### **I am unsure about the energy / momentum gain, that a particle with a non-nominal q/m ratio receives in an RF cavity:** 

According to the code (if I understand it correctly) the momentum gain in an RF cavity is 

$p_\tau \leftarrow  p_\tau + \dfrac{q}{m_0 \beta_0 \gamma_0 c^2} V \sin (phase)$, 

where $m_0$ corresponds to the **mass of the reference particle** but $q$ to the **charge of the particle with non-nominal q/m**. 
This is taken from https://github.com/xsuite/xtrack/blob/main/xtrack/beam_elements/elements_src/cavity.h (line 31)
```
        double const   q      = fabs(LocalParticle_get_q0(part))
                		        * LocalParticle_get_charge_ratio(part);
        double const   tau    = zeta / beta0;

        double const   phase  = DEG2RAD  * (lag + lag_taper) - K_FACTOR * freq * tau;

        double const energy   = q * volt * sin(phase);

        #ifdef XTRACK_CAVITY_PRESERVE_ANGLE
        LocalParticle_add_to_energy(part, energy, 0);
        #else
        LocalParticle_add_to_energy(part, energy, 1);
        #endif
```
with
```
      void LocalParticle_add_to_energy(LocalParticle* part, double delta_energy, int pz_only ){
          double ptau = LocalParticle_get_ptau(part);
          double const p0c = LocalParticle_get_p0c(part);

          ptau += delta_energy/p0c;
          ....
```
However, in the user guide (chapter 1.4.5, acceleration cavity), the momentum gain is derived as

$p_\tau \leftarrow p_\tau + \xi \dfrac{q_0}{P_0 c} V \sin \left(\Phi - k \tau + k \dfrac{s-s_0}{\beta_0} \right)$

$p_\tau \leftarrow p_\tau + \dfrac{q}{q_0} \dfrac{m_0}{m} \dfrac{q_0}{P_0 c} V \sin \left(\Phi - k \tau + k \dfrac{s-s_0}{\beta_0} \right)$

$p_\tau \leftarrow p_\tau + \dfrac{q}{m \gamma_0 \beta_0  c^2} V \sin \left(\Phi - k \tau + k \dfrac{s-s_0}{\beta_0} \right)$, 

**i.e. with a factor of** $\dfrac{1}{m}$ **instead of** $\dfrac{1}{m_0}$ **, which is in agreement with my understanding.**

### Example: 
I attached a figure, in which I track He-2+ and C-6+ ions with a mass ratio of $m / m_0 \approx 4/12 = 1/3$, but $chi=0.99935$ in a stationary bucket. C-6+ (orange) is the reference particle.  The particles are all initialized with $zeta=0$ and different $delta$ (scatter markers). The figure shows the phase space trajectories when tracking the particles over  100k turns. We see that

* The synchronous He-2+ ion seems to have the correct $\delta$ offset, which is in agreement with $\dfrac{\Delta \beta_\text{He}}{\beta} = \dfrac{1}{1/\alpha_c - \gamma_0^2} \cdot \left(1 / \chi - 1\right)$, as analytically derived when considering $f_\text{rev,he} = f_\text{rev,c}$.

* However, both the bucket height of He-2+ as well as the small-amplitude synchronous tune of He-2+ (obtained by FFT) seem to be reduced by a factor $1/\sqrt{3}$, which is in agreement with $\sqrt{m/m_0}$

  - Bucket height He: $\hat{\delta} \approx 0.0012$, C: $\hat{\delta} \approx 0.002$ --> factor $\sqrt{1/3}$
  - $Q_{s,\text{He}} \approx 0.0013$, $Q_{s,\text{C}} \approx 0.0023$, --> factor $\sqrt{1/3}$

![grafik](https://github.com/xsuite/xsuite/assets/130861074/62ee3e05-11ca-4624-b4e9-2f4e56dfbab7)

Thanks a lot for your help and please let me know if you need further info (e.g. example code). 

Kind regards, Elisabeth 

PS: Thanks a lot for providing the feature of tracking non-nominal $q/m$!

**Comment by giadarol** [comment]
It is very possible that this is a bug. Although the code is designed to support particles of different species simultaneously, this feature has not been fully validated nor used so far (and it is presently not covered by the automatic tests).

As this is needed for some applications, we should invest some times in checking this aspect in Jan/Feb 2024.

(@phermes was also looking into this)

**Comment by elisabethrenner** [comment]
Many thanks for the fast reply and the intention of looking into it soon! 

We fully understand that this feature is only under development and not fully tested. We will keep using it (with caution) for unbunched beams in the meantime and let you know in case we notice irregularities. 

Thanks for keeping us updated and happy new year!

**Comment by elisabethrenner** [comment]
Dear Giovanni and all, 

I hope you've all had a nice Christmas break. While continuing to validate our simulations for ions with $\chi \neq 1$ - for now for coasting beams - I came across one more issue, which I don't fully understand:

Can it be, that the factor $\chi$ is missing when computing the dipole edge focusing? 
https://github.com/xsuite/xtrack/blob/main/xtrack/beam_elements/elements_src/dipoleedge.h

E.g. in lines 46 and 47 (or their equivalents)

```
            LocalParticle_add_to_px(part, r21*x / chi);
            LocalParticle_add_to_py(part, r43*y / chi);
```

instead of 

```
            LocalParticle_add_to_px(part, r21*x);
            LocalParticle_add_to_py(part, r43*y);
```

With this correction, 
$p_x \rightarrow p_x + \dfrac{1+\delta}{\chi} \dfrac{\tan(\alpha)}{\rho} \cdot x $, 
a particle with non-nominal charge-to-mass ratio ($\chi \neq1$) and $\delta$ would receive the same kick due to the dipole edge as a particle with reference charge-to-mass ($\chi=1$), but an effective momentum offset $\delta_\text{eff} = \dfrac{1+\delta}{\chi}-1$, which is expected if I understand correctly.

Please let me know if I misunderstand sth! If this is true, it is currently no show-stopper for us, but it will help me explain the slight offset in the tune distribution which I observe in our simulations. 

Please let me know if I can help with further info, discussion or a short example file.

Thank you for your efforts!
Elisabeth

PS: Please note, that I corrected the label of the figure in the initial bug report. The y-axis displays of course $\delta = \dfrac{\beta \gamma - \beta_0 \gamma_0}{\beta_0 \gamma_0}$.

**Comment by phermes** [comment]
Hi Elisabeth, 

thanks for spotting this and sorry for my late reply. I checked the math and you are right: the change of $p_\tau$ should indeed be proportional to $q_0 \chi =  q \frac{m_0}{m}$. See page 115 in this document: 

https://cds.cern.ch/record/2241364/files/CERN-THESIS-2016-230.pdf

My benchmarks were performed by analysing the synchrotron tune for two particles of different charge but with identical mass (more concretely fully and partially stripped Pb208). In this scenario, the issue you flagged was not visible: I should have tested also nuclides of different masses. 

We are about to get started simulating multi-nuclide beams in Xsuite at CERN as well and plan to implement more robust unit tests, as Gianni mentioned. And of course, we will also review the physics model of the cavities to fix the bug. If you have already your own, fixed, implementation, feel free to launch a pull request.

Thanks again and have a nice day.
Pascal

**Comment by elisabethrenner** [comment]
Hi @phermes, 

Thank you for the detailed response! We have focused on coasting beams for now, so we don't have a fixed implementation for now but I'll let you know/launch a pull request if we do! 

Can I also ask you for your opinion on the second issue, i.e. the focusing in the dipole edges for $\chi \neq 1$ (see my last comment above)? 

Honestly, thanks a lot for your input and efforts! 

Have a nice day, 
Elisabeth

**Comment by elisabethrenner** [comment]
Hi @phermes, 

I've just noticed, that I made a mistake when describing the issue about the dipole edge above. I of course meant that a factor $\cdot \chi$, not $1 / \chi$ is missing. I edited the description accordingly. 

Anyway, I corrected the error locally as described and it works well for me! 

Cheers, Elisabeth
