### ISSUE TITLE
Duplicate Scaling in px and py Leading to Decrease in Normalized Emittance

### ISSUE THREAD

**Issue by ErikKvikne** [xsuite/xsuite#451]
We've noticed an issue in accelerators with large energy increases: there's a decrease in normalized emittance. Here's a screenshot showing this:

![Screenshot from 2024-01-11 15-27-54](https://github.com/xsuite/xpart/assets/87233978/2f37bb56-32e5-4dca-a74a-d33165fb2112)

This seems to be caused by the scaling of px and py happening twice, once in [linesegmentmap.h](https://github.com/xsuite/xtrack/blob/da0c56095e203fdab587bfe66984a0b970ede5c4/xtrack/beam_elements/elements_src/linesegmentmap.h#L315C1-L319C58) and then in the [LocalParticle_update_p0c()](https://github.com/xsuite/xpart/blob/main/xpart/particles/particles.py#L149C1-L152C69) function. 

It seems like removing line 149-152 in [LocalParticle_update_p0c()](https://github.com/xsuite/xpart/blob/main/xpart/particles/particles.py#L149C1-L152C69) makes the normalized emittance remain constant:

![Screenshot from 2024-01-11 15-31-25](https://github.com/xsuite/xpart/assets/87233978/8f53282c-2bf3-44f4-bdfd-f84cd73004aa)

But we are not sure if this is the best fix.

**Comment by ErikKvikne** [comment]
Yes, [this](https://github.com/xsuite/xtrack/blob/main/examples/transfer_matrix/001_MuonCollider_example.py) example script illustrates the issue. Based on my understanding, the quantity shown in Figure 3 is expected to be invariant. However, as the number of turns increases, we observe a reduction:

![invariant_original](https://github.com/xsuite/xpart/assets/87233978/f1311405-d0b5-468a-a1d2-a8f4ede67f2c)

When we remove the lines in the `LocalParticle_update_p0c()` function, the invariant appears to stabilize:

![invariant_edited_xpart](https://github.com/xsuite/xpart/assets/87233978/b71d3b7f-66d9-4a92-bd2e-ca91a7a7f702)

**Comment by giadarol** [comment]
We cannot touch `LocalParticle_update_p0c` because it is needed as is in other places of the code.

I propose instead the following fix:
https://github.com/xsuite/xtrack/compare/fix/acceleration_in_line_seg_map?expand=1#diff-3a304ffb86d54dd58c5d056c212588896ae33cdc110fbcc96b75e00b32fcda81

@xbuffat  do you agree?

**Comment by giadarol** [comment]
Done (xtrack v0.48.2)
