### ISSUE TITLE
Twiss fails when importing a json file with Line.from_json under Windows 11

### ISSUE THREAD

**Issue by chanceant** [xsuite/xsuite#453]
Dear all,

When I import a Line from a json file (diretcly generated by XSuite with xt.Line.to_json), I get an odd behaviour of XSuite.
Indeed, under Windows and Ubuntu, the import works well and I get the right feature of the line (the number of elements, total length and attributes of the elements seem all right when I use get_table).
However, when I use Twiss just behind, I get the right behaviour with Ubuntu but the method fails with Windows.

As an example, I put in attachment a simplified json file.

The test was done with the last release Xsuite 0.6.0.

Thank you for your answer and the great work you do.

[lattice_disp_suppr.json](https://github.com/xsuite/xsuite/files/14084015/lattice_disp_suppr.json)

The code I have run is the following:

```
import xtrack as xt
# Loads the json file
lattice = xt.Line.from_json('lattice_disp_suppr.json')
lattice.build_tracker()

# Prints the attributes of the line; works with Linux/Ubuntu and Windows 11
lattice.get_table().show()

# Works only with Linux/Ubuntu. 
# Fails with Windows 11 (elements are not corretly loaded with a length of 0  for all of them for instance)
tw = lattice.twiss(method="4d")
print(tw)
```

**Comment by giadarol** [comment]
In fact we do not us support Windows. Our suggested way for running Xsuite in Windows is to do it within [WSL](https://learn.microsoft.com/en-us/windows/wsl/install).
