### ISSUE TITLE
TypeError in xobjects when loading from_json a line containing a FirstOrderTaylorMap

### ISSUE THREAD

**Issue by gbrogginess** [xsuite/xsuite#457]
The TypeError can be spotted by running the following piece of code:

`import numpy as np
import xtrack as xt

m0 = np.arange(6,dtype=float)
m1 = np.ones((6,6),dtype=float)

elements = {
    'a': xt.FirstOrderTaylorMap(radiation_flag=0, length=1.0,
                                m0=m0,
                                m1=m1),
}

line = xt.Line(elements=elements, element_names=['a'])

line.to_json('simple_line.json')

line = xt.Line.from_json('simple_line.json')`

TypeError: list indices must be integers or slices, not tuple

**Comment by giadarol** [comment]
Can't reproduce this with the latest versions of xsuite. 

@gbrogginess Could you try again after updating all packages? Don't hesitate to reopen the issue if the problem persists.
