### ISSUE TITLE
Wrong calculation of the chromaticity when using periodic lattice and using start/end

### ISSUE THREAD

**Issue by chanceant** [xsuite/xsuite#458]
Dear all,

I would like to match the chromaticity of some arc cell.
If I use the method twiss by setting "periodic" for the beta init and start/end to markers, the calculation is wrong.
For instance, Mad-X gives 0.358/0.325 in each plane whereas XSuite gives 0.17/0.4 for instance.
If I change the initial point by using cycle, the value of the chromaticity also changes in XSuite, which should not.
Apparently (but that is only a suggestion), the problem comes from the file twiss.py line 1183, the calculation of the RR_chrom matrix does not include the starting and final point. If I add the options start=start and end=end, it works nicely and I find again the values given by Mad-X.

Thank you again for considering this issue,

**Comment by giadarol** [comment]
Thank you for spotting this! Indeed we had never tested the chromaticity from a portion of a beam line.
Indeed the fix you propose is all that should be needed.
Release with the fix should be coming soon.

**Comment by giadarol** [comment]
Should be solved now (xtrack v0.52.0)

@chanceant Don't hesitate to reopen if you still see issues.
