### ISSUE TITLE
nafflib returning negative frequency for real data

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#461]
For now introduced this patch in get_amplitude_detuning_coefficients:
https://github.com/xsuite/xtrack/blob/6187a7845cebd968bb84ce3b17476d65de94ebf1/xtrack/line.py#L1582

To be removed when this is sorted

**Comment by pbelange** [comment]
Fixed!

**Comment by pbelange** [comment]
See nafflib 2.0.1 with the following changes:
https://github.com/xsuite/nafflib/commit/65ab275b085d4c228154877c61139505a9eef300
```
- Fixed negative tunes values (parse_real_signal) with new test
- Changed default window_order to 2
- Centralized to_pandas to only be applied/used in nafflib.harmonics()
- typo in setup
```

**Comment by giadarol** [comment]
@pbelange thanks. I will remove the patch
