### ISSUE TITLE
Optimize_for_tracking fails for an xmask collider

### ISSUE THREAD

**Issue by kparasch** [xsuite/xsuite#462]
Raises ```NotImplementedError: `remove_inactive_multipoles` not available when deferred expressions are used``` even though the deferred expressions are supposed to be removed in the first step of optimization.

Example:
```
import xtrack as xt
line = xt.Multiline.from_json("../../test_data/hllhc15_collider/collider_00_from_mad.json").lhcb1
line.build_tracker()
line.optimize_for_tracking()
```

**Comment by giadarol** [comment]
Indeed this was never tested for multiline.
Fix here: https://github.com/xsuite/xtrack/pull/443

Would be good to add a test before merging

**Comment by giadarol** [comment]
Done (xtrack v0.52.0)
