### ISSUE TITLE
NotImplementedError: Field errors are not yet supported for thick elements

### ISSUE THREAD

**Issue by BhawinDhital** [xsuite/xsuite#473]
Hi,

I am trying to work with extraction bumps in Xsuite. However it gives me the following error:

NotImplementedError: Field errors are not yet supported for thick elements

Sincerely,
Bhawin

**Comment by giadarol** [comment]
These are now provided.

See:
https://xsuite.readthedocs.io/en/latest/line.html#apply-transformations-tilt-shift-to-elements
https://xsuite.readthedocs.io/en/latest/line.html#add-multipolar-components-to-elements
