### ISSUE TITLE
reduce typing to add enable/disable vary/target tag/id in xdeps.Optimizer

### ISSUE THREAD

**Issue by rdemaria** [xsuite/xsuite#492]
Proposals

- `opt.enable(targets="ip",vary=[2,3]).disable(targets="phase",vary=["kqx.l1"]).step(...)` : permanent
- `opt.step(.., enable_targets="ip",vary=[2,3], disable_targets="phase",vary=["kqx.l1"])` : temporary in the step

Argument of enable/disable:
-  if is list/tuple list of arguments 
-  elif integer arguments is id
- else argment is tag

**Comment by giadarol** [comment]
Implemented
