### ISSUE TITLE
Is quadrupole fringe implemented?

### ISSUE THREAD

**Issue by bogomyag** [xsuite/xsuite#495]
I looked through physics manual and got an impression that there is no implementation of quadrupole fringes (thin, octupole like), only for combined function dipole, which are different from pure quadrupole.
Is this correct understanding?
When will quadrupole fringes be implemented like in MADX-PTC for example?
This is necessary for collider dynamic aperture calculations like FCC-ee and others.

**Comment by giadarol** [comment]
Indeed this is not implemented yet. We could implement it over the coming weeks. 

@bogomyag It would be very useful if you could test and validate our implementation.

**Comment by bogomyag** [comment]
Hi, I am glad and interested in testing it. However, I need help with installation x-suite on windows 10. I was able to install and run it on CPU, but not on AMD graphics card. I understood that AMD stopped releasing compilers on windows 10. Not sure if I am correct.

**Comment by johnmssmith** [comment]
> Indeed this is not implemented yet. We could implement it over the coming weeks.

Hi, I'm interested in that as well. Any progress?

**Comment by szymonlopaciuk** [comment]
Hi, we have multipolar fringes now implemented for Quadrupole, Sextupole, and Octupole elements. These can be enabled using the properties `edge_entry_active` and `edge_exit_active` of the elements. You can have a look at [this test](https://github.com/xsuite/xtrack/blob/0ac22aeefb72b69b9c56ff1b47185ccc786f78b8/tests/test_elements_thick.py#L1433) as an example.

**Comment by szymonlopaciuk** [comment]
I'll close this, but feel free to reopen if you have any questions/issues!

**Comment by bogomyag** [comment]
I have opened a new issue about discrepancy between MADX-PTC and xsuite, because I have no rights to reopen this issue.
#593
