### ISSUE TITLE
xobjects contexts/buffers concepts explanation

### ISSUE THREAD

**Issue by kparasch** [xsuite/xsuite#9]
Diagram would be nice explaining how the contexts, buffers, trackers, lines, particles are related to each other.

Could start by adding to documentation:
 - in UserGuide: explanation on general features of HybridClasses (_xobject, _XoStruct), copy, move, to_dict
 - Need to introduce the concept of buffer
 - Better explain difference between tracker and line (maybe a section about Line and a section about Tracker is a good idea)

**Comment by giadarol** [comment]
Introduced new section in documentation addressing the points above: 
https://xsuite.readthedocs.io/en/latest/xsuite_data_management.html

PRs with further improvements are welcome :-)
